apiVersion: v1
kind: Namespace
metadata:
  name: cray
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cray
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    nodePort: 30000
  selector:
    app: mysql
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: cray
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0.12
    env:
    - name: MYSQL_USER
      value: mysql
    - name: MYSQL_PASSWORD
      value: mysql
    - name: MYSQL_DATABASE
      value: sample
    - name: MYSQL_ROOT_PASSWORD
      value: supersecret
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: local
      mountPath: /var/lib/mysql
  volumes:
  - name: local
    hostPath:
# Change this to a local directory
#      path:
      type: Directory